#if EXT_TYPE == 0
"bzclose", T(Variant), S(0), "bz", T(Object), NULL, S(0), NULL, S(0), 
"bzcompress", T(Variant), S(0), "source", T(String), NULL, S(0), "blocksize", T(Int32), "4", S(0), "workfactor", T(Int32), "0", S(0), NULL, S(0), 
"bzdecompress", T(Variant), S(0), "source", T(String), NULL, S(0), "small", T(Int32), "0", S(0), NULL, S(0), 
"bzerrno", T(Int32), S(0), "bz", T(Object), NULL, S(0), NULL, S(0), 
"bzerror", T(Variant), S(0), "bz", T(Object), NULL, S(0), NULL, S(0), 
"bzerrstr", T(String), S(0), "bz", T(Object), NULL, S(0), NULL, S(0), 
"bzflush", T(Variant), S(0), "bz", T(Object), NULL, S(0), NULL, S(0), 
"bzopen", T(Variant), S(0), "filename", T(String), NULL, S(0), "mode", T(String), NULL, S(0), NULL, S(0), 
"bzread", T(Variant), S(0), "bz", T(Object), NULL, S(0), "length", T(Int32), "1024", S(0), NULL, S(0), 
"bzwrite", T(Variant), S(0), "bz", T(Object), NULL, S(0), "data", T(String), NULL, S(0), "length", T(Int32), "0", S(0), NULL, S(0), 
#elif EXT_TYPE == 1
#elif EXT_TYPE == 2
#elif EXT_TYPE == 3

#endif
