
PROJECT_ROOT = ../../..
PROJECT_NAME = hphp_cpp_ext

AUTO_SOURCES = 1
SOURCE_SUBDIRS = bcmath hash fql phpmcc mailparse

include $(PROJECT_ROOT)/src/rules.mk

TARGETS = $(STATIC_LIB) $(SHARED_LIB)

all: $(TARGETS)
